(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 480,
	fps: 21,
	color: "#FFFFFF",
	manifest: [
		{src:"images/Bitmap1.png", id:"Bitmap1"}
	]
};



// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,149,123);


(lib.OlafUpperBod = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AHNAUQAfDEjUBPQjUBOjXgMQjZgMg0hMQg0hNAEibQAEiaByh4QByh5DRgHQDOgIB8BiQB7BhAfDCg");
	this.shape.setTransform(46.6,36.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAJiKYAHAEAGADAHAEIAJAFYAEACACACADACYADACAEACACACIAHAIYADADACADABADIAGAJIALATYACAHADAGACAHYADAHABAHACAHIABAEIABAGIABADIAAABIAAAAYAAgCAAACAAgBIAAAAIAAABIAAAAIAAAGYAAAEAAACAAADIgBAKYgBAGgDAHgBAHIgHAUYgCAGgDAIgDAGIgFAIIgGAJYgCADgDACgCACYgCADgDACgCABYgDACgCACgDACYgDABgDACgDABYgDABgDABgDAAIgKACIABAAYgCAAgDAAgCABIABgBIgLAAYgEgBgCAAgDgBYgIgCgHgCgHgEYgDgBgDgCgDgDIgFgDIgFgEYgDgCgCgDgDgDYgBgBgCgCAAgBIgEgFIgIgKYgCgDgCgDgCgEYgEgGgDgIgEgHYgCgDgBgEgBgEIgEgLIgFgWIgCgMIAAgMYAAgEABgEAAgEYAAgEABgDABgEYABgEACgEABgEYABgDACgEACgDYACgEACgDACgEYACgDADgDACgDYACgDAEgDADgDYADgDADgCADgDYAEgCADgCADgCIALgGIAMgGIALgEYAEgBAEgBAEgBYADAAAEAAAEgBAAJiKYgEAAgEAAgDAAYgEAAgEAAgEABIgNADIgMAEYgEACgEACgEABYgEACgEADgDACYgEACgEADgDACYgEADgDACgDAEYgDADgDADgDAEYgCADgDAEgDAEYgCAEgCADgCAEYgCAFgBAEgCAEYgBAEgBAEgBAFYgBAEgBAFAAAEYAAAFgBAFABAEIAAANIAFAXIAEAOYABAEABAEACAEYAEAIADAIAFAIYACAEACAEADAEIAHAKIAEAFYACADABABACACYADADADADADADIAGAFIAFAEYAEADAEACAEACYAIAEAJADAJACYAFACAEAAADABYAEAAAFAAAFAAIABAAYACAAABAAABAAIABAAIAMgCYAEgBAEgCAEgBYAEgBAEgCADgCYAEgCADgDAEgCYADgDADgCADgDYACgEAEgCACgEIAHgKYACgDABgEACgDYAEgIACgGADgIYACgHACgHACgIYACgHACgHAAgJIABgMYABgEgBgBAAgEIgBgFIAAgBIAAAAIAAgCIAAAAIAAgBIgBgDIgBgFIgCgGYgCgHgCgIgDgHYgDgHgEgGgDgHIgMgTIgHgJYgDgDgCgDgDgDIgIgHYgEgDgDgBgDgCYgDgCgEgCgDgCIgKgEYgHgDgHgCgHgD");
	this.shape_1.setTransform(68.1,41.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1C1C1C").s().p("AhABgQgbgggLgpIgFgXQgIg3AlgoQAQgQAXgLQAbgMAVABIAHADQAbALAPALQALAKAKAQQANAVAGAPQAEAJAFAVIACAKQAEAbgPArQgYBCg1AEIgFAAIgCAAQguAAgggmg");
	this.shape_2.setTransform(68.1,41.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiTFpQjZgMg0hMQg0hNAEibQAEiaByh4QByh5DRgHQDOgIB8BiQB7BhAfDCQAfDEjUBPQi4BEi5AAQgdAAgdgCgACuhJQgXALgQAQQglAoAIA1IAFAZQALApAbAgQAgAnAygBIAFAAQA1gEAYhCQAPgrgEgdIgCgKQgFgVgEgJQgGgNgNgVQgKgQgLgKQgPgLgbgLIgHgDIgFAAQgVAAgYALg");
	this.shape_3.setTransform(46.6,36.3);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,95.2,74.7);


(lib.olafRighArm = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#330000").s().p("ACiAmYgRgMgPgNgPgNYgPgNgOgOgMgQYgMgQgKgSgPgOYgDgDgEgEgFgDYgCgBgDgBgCgBIgKgCYgGgBgEgBgGgCYgFgBgFgDgDgEIAAAAYgBACgCACgDABYgCACgDABgEAAYgHACgIABgHABYgEAAgDACgDABYgDABgCACgBABYgDAEgDAEgCAFYgFAIgDAJgDAKYgCAKgCAKgDAKYgDAJgFAJgFAIYgFAHgFAIgFAIYgLAQgMAPgPAOYgNALgBAUALANYAMAMATABANgLYAFgEADgGABgGYAFgTAIgSAJgRYAEgJAFgJAFgIYAFgIAGgHAHgGYAHgHAIgHAHgHYAIgHAHgHAFgIYADgEACgEACgFYABgCAAgDAAgDYAAgDgBgDgBgEYgDgHgCgHgDgHYgBgEAAgDAAgCYAAgDABgDABgCIAAAAYADAEACAFABAGYABAGABAGAAAGIABAJYABADAAADABADYACAEADAEADAFYAKAQARAMAPANYAPANALAPANAQYALARAMAQAJATYAJARAVAHASgJYARgJAHgVgJgRYgDgGgEgEgFgD");
	this.shape.setTransform(35.3,94.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#330000").s().p("AAGiHYAAAAgBABgCACYgCABgBADgBADYgDADgCAEgDAEYgDAFgCAFgCAGYgEALgCANAAAOYABAHABAHABAIYACAHACAIABAHYABAIAAAHAAAGYAAAHgBAHAAAHYgBAOgCAOgBALYgCALgCAJgCAHYgCAGgBAEAAAAYgFANAHAPAOAFYALAEAPgHAEgNYACgFAAgFgBgFYAAAAgBgEgBgGYgBgHgBgKgBgLYgBgLgBgNAAgOYABgHAAgIAAgHYAAgGACgHABgHYACgIACgHADgIYACgHACgHAAgHYACgOgBgNgDgMYgBgFgCgGgDgEYgCgFgCgEgCgDYgCgEgCgCgCgCYgCgCAAgBAAAAIAAAA");
	this.shape_1.setTransform(32.4,97.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#330000").s().p("AhMgWYAAAAAAABAAABYABACABACABACYABADACACACADYACACACADADABYACABADACAEACYADABAEgBAEAAYAFgBAEAAAEACYAEABAEACADADYAEACAEADAEABYADACACACAEABYAHADAHADAGACYAMAFAIACAAAAYAOAEAOgIAFgNYAEgOgIgMgOgFYAAAAgIgCgMgDYgGgCgHgBgIgCYgEgBgEgBgEAAYgEgBgDAAgEAAYgFAAgEgBgEgBYgEgBgEgCgDgDYgDgDgDgDgEAAYgDgCgEABgDAAYgEAAgDABgDABYgDABgDACgCABYgDABgCABgBABYgBABgBABAAAAYgBABgBACABAC");
	this.shape_2.setTransform(38.8,80.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#330000").s().p("AjJmHYAJAhALAhAMAiYAGAQAFARAGAQYAHAQAFARAIAQYAHAQAJAQAIAQYAIAQAHAQAHAQYAGARAEARAEASYAEARADASAGAPYAGAQAHAQAIAQYAIAQAIAQAIAQYAPAfAQAfAOAhYADAIAEAIAEAIYADAIADAIADAJYAHAQAFARAGARYAMAhAPAhARAeIgBgDYADAIAEAIAFAIYAEAIAEAHAFAIYAMARAWAEARgLYAMgIAFgOgBgOYgCgJgCgJgCgIYgCgJgDgJgDgIIgBgEYgNgggQgfgTgeYgJgPgJgOgJgPYgJgPgJgPgGgRYgOgfgLgigLghYgFgQgFgRgGgQYgGgRgHgOgGgQYgHgQgIgPgHgPYgIgQgIgPgGgQYgGgRgFgQgFgRYgDgRgFgRgDgRYgEgSgFgQgEgRYgFgRgFgRgFgRYgLghgKghgNghYgJgYgagMgYAJYgXAIgMAZAHAX");
	this.shape_3.setTransform(15.9,40.7);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.5,-4.4,57.7,115.6);


(lib.OlafLowerBod = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Bitmap1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,149,123);


(lib.OlafLeftLeg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ADfCoQBnh1gNh0QgNh2iDgwQiDgwh3gPQh5gPhABhQhABfAXBNQAXBKBJCJQBJCICCgLQCAgMBnh0g");
	this.shape.setTransform(31.5,29.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjTCsQhJiJgXhLQgXhNBAhfQBAhhB5APQB3APCDAxQCDAvANB2QANB0hnB1QhnB0iAAMIgUABQh0AAhDh9g");
	this.shape_1.setTransform(31.5,29.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,65,61.5);


(lib.OlafLeftArm = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#330000").s().p("AlSktYAAAAALAKARARYASARAZAZAeAfYAPAPAQAQAQASYARASASASARAUYASAUARAVASAVYATAVATATASAVYAJALAJALAKALYAHAKAKAKAKAKYATAUAWARAUARYAVARATARASARYARARAPARAOAQYAOAQAMAPALAOYALAOAIAMAIAKYAHALAFAIADAGYAEAFACAEAAAAYALATAaAHATgMYAUgLAHgagMgUYgDgFgEgEgFgDYAAAAgDgCgFgEYgGgEgHgGgKgIYgKgIgLgKgNgMYgNgLgOgOgOgPYgPgPgQgRgPgTYgQgSgPgVgPgWYgQgWgQgXgRgVYgJgLgJgLgKgKYgKgIgKgJgKgKYgUgVgRgUgTgVYgTgUgVgSgSgTYgTgTgQgUgQgSYgQgSgQgSgNgPYgcghgXgbgQgTYgQgTgIgLAAAAYgQgTgcgEgUAQYgTAPgEAdAQATYABACACACABAB");
	this.shape.setTransform(30.6,33.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#330000").s().p("AANhKYAAAAgBAAgCABYgBAAgCACgDABYgBABgBABgCAAYAAABAAABgBACYgDACgDACgCADYgCADgCAEAAADYgBAEABAFACAEYABAFABAEgBAFYgBAEgCAEgCAEYgCAEgDAEgCADYgBAEgCAEgBAEYgEAIgBAHgBAHYAAAHAAAGAAAEYABAEAAACAAAAYADALAMAHALgDYAEgBACgDADgDYAAAAABgCACgEYACgDADgFACgHYACgGACgIAAgIYABgEAAgFAAgEYAAgFgBgEAAgDYAAgFAAgEABgFYABgEACgEADgDYAEgEADgEAAgDYABgEAAgEgBgDYAAgEgCgDgBgDYgBgCAAgBgBgCYgBgBgBgBgBgCYgCgCgBgCgBgBYgBgCgBAAAAAAYgBgCgCAAgCAB");
	this.shape_1.setTransform(52.4,68.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#330000").s().p("AB5ASYgLgEgLgEgLgFYgKgFgLgDgKgFYgKgGgKgFgKgGYgKgFgKgHgHgGYgSgOgSgPgRgPIgHgGIgDgDIgCgBIAAgBYAAABABgBgCABIAAAAIAAAAIAAAAIgBAAYgFgDgFgCgGgDYgKgFgKgGgKgFIgCgBYgHgFgKADgEAHYgCAEAAAEAAADYABAFACAFAAAFIABACYAAADABACACACYAIAHAIAIAIAIYAHAIAIAIAGAJYAHAJAHAJAGAJYAGAHAGAKAGAJYAMASASAOARAOYAHAHAIAHAHAIYAIAIAHAJAFAKYAGALANADAKgFYALgGADgNgFgKYgCgDgCgDgDgCYgKgGgIgIgHgIYgIgIgGgJgGgJYgNgSgMgTgPgMYgJgHgJgGgJgIYgIgHgJgHgIgHYgIgIgHgIgHgIYgIgJgHgIgHgJIAEAJYAAgGAAgFgBgFIgYAPYAJAHAJAHAJAIYAEADAFAEAEAEIABABIAAAAIAAAAIAAAAYgBACABgCAAABIAAAAIACABIAEACIAIADYAVAKAVAKAUALYAJAGAIAGAJAHYAKAFAJAHAJAHYAIAIAJAHAJAIYAIAIAJAHAIAJYAKALARABALgLYALgKABgRgKgLYgEgDgDgDgEgB");
	this.shape_2.setTransform(73.3,75.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#330000").s().p("AgRhwYAAAAAAABgBACYgCACgBACgCADYgBACAAACgBACYgBABgBADAAACYgBAEgCAFAAAFYgBAFAAAGABAGYABAFADAGADAGYADAGADAGAAAHYABAGABAHAAAHYAAAMgCAOAAAMYAAAHgBAGABAGYAAAGACAFAAAFYAFAUAGANAAAAYAEAJAJAFAKgEYAGgDAEgGABgGYAAAAACgOAAgUYgBgFAAgGgBgGYgBgFgCgGgCgGYgDgNgFgNgEgLYgCgGgBgHgBgHYgBgGABgHABgHYACgGABgHAAgFYAAgGgCgFgCgFYgCgFgCgFgDgDYgBgCgBgCAAgCYgBgBgBgCgBgBYgDgDgCgCgBgBYgCgCgBAAAAAAYgBgCgCAAgBACYAAAAgBAAAAAA");
	this.shape_3.setTransform(62.8,77.9);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.7,-4.7,91.9,94.1);


(lib.olafHead = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(0.1,1,1).p("AhwjnQAAAdgUAUQgVAVgdAAQgdAAgUgVQgVgUAAgdQAAgdAVgVQAUgUAdAAQAdAAAVAUQAUAVAAAdgAh+CDQgggfgJg6QgJg5A3gpQA4gpBCAJQBEAIAlAWQAaAPATAlQAIANANAmQAFAOAKAjQAKAjAMAbQAeBDAIAXQAHAXgBADQgCACAAADQAAAKgHAHQgHAIgIAAQgHABh1gtQhzgtgrgZQgqgagfgfgACSihQAAAdgUAUQgVAVgdAAQgdAAgUgVQgVgUAAgdQAAgdAVgVQAUgUAdAAQAdAAAVAUQAUAVAAAdg");
	this.shape.setTransform(79.8,130.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAwCPIAUgPYAGgFAGgGAGgGYAGgGAGgHAFgHIAGgLIACgDYABgBAAgBAAgBIADgGYADgHACgJADgIYACgJACgIABgIIABgNYAAgBAAgBAAgCIAAgCIABgFIAAgNYAAgEgBgFgBgEYAAgEgBgFgBgEIgDgNYgCgJgFgIgEgIYAAgBAAAAgBgCIgCgDYgBgBgCgDgCgCYgDgDgDgEgDgCIgDgDIgBgBIgBgBIgBAAIgFgEIgKgHYgEgDgEgCgEgCYgDgBgBgBgDgBIgGgCIgMgEYgEgCgEAAgFgBYgEgBgEgCgFAAYgEAAgEgBgDAAYgJgBgKABgKAEIABgBYgEACgFABgEACYgFACgFACgEADIgGADYgCACgCACgCABYgCACgDACgBABIgFAFYgDADgDAEgDAEIgFAGIgEAFIgEAGYgBACgCABgBACIgHAOIAAgBIgDAIYgCACgBADgBACIgCAIYgBADgBACgBADIgCAIYAAACgBADAAADIgDAQIAAAAIAAAAYABAPABARACAQIAAAAYABgQABgRABgPIAAAAIAEgOYAAgDABgCABgDIADgHYABgDABgCABgCIADgHYABgCABgDACgCIADgGIABgBIAGgKYABgCACgCABgCIAFgFIAEgFIAFgFYADgDACgDADgDIAFgFYACgBACgBABgCYACgBABgBACgBIAGgDYADgCAEgBAEgCYAEgBAEgBAEgCIABAAYAGgCAHAAAIAAYABAAAFABAEAAYADABAEABAEABYADABAEAAAEABIAMAFIAGABYABABACABABABIAKAFIAKAHIAFAEIAAAAIAAAAYgBgBABABAAAAIAAAAIAAAAIABABIACACYADADADADACACYACABAAABACACIABACIACADIAFAKYAAACACABAAACIACAGIADALYACAEAAADABAEYAAAEABADAAAEIABANIAAAFIAAACIAAADIgBAMYAAAIgBAIgCAIYgBAIgCAHgCAIIgCAGYAAABgBACAAAAIgBADIgFAKYgEAHgFAHgFAHYgFAGgFAGgGAGIgRASIAAAA");
	this.shape_1.setTransform(90.2,114.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ACHgZYAAAAAAADAAAHYAAADAAAFgBAEYAAADAAAFgCAHYgBAMgEAOgHAPYgDAIgFAIgFAIYgCAEgDADgDAEYgDAEgDAFgDAEYgNAPgSANgVAJYgLAEgMADgMACYgDABgIABgGAAYgGgBgGABgGgCYgagDgYgQgPgXYgJgLgGgMgGgNYgFgNgDgOgBgOIgBgKIABgKYABgGABgGABgHYAAgHADgGABgHYABgHADgGACgGYACgDABgDABgDIAEgJIAFgJIAGgIIAFgJIAGgHYAEgFAFgEAEgFYACgCADgCACgBYABgBABgCABAAIAEgCYAGgEAFgBAFgDYAGgBAFgDAGAAYADgBADgBACAAYADAAADgBADAAYAUgCAWAFATAIYAEACAFACAEACYAEADAEACAEADYAEADAEACADADYADADADADADADYAMAMAHANAFALYABADABACABADYABACABADABACYACAFABAEAAADYACAGABAEAAAAACJgZYAAAAAAgEgBgHYAAgDgBgEgBgFYAAgDgBgCAAgDYgBgDgBgDgBgDYgDgMgGgPgMgPYgDgDgDgEgDgEYgEgDgDgDgEgDYgFgEgEgDgEgDYgFgDgFgDgFgCYgUgKgZgHgZABYgDAAgDABgDAAYgEAAgDABgDABYgHABgHACgGACYgHADgIADgFADIgEADYgCABgBABgCACYgDACgDACgCADYgFAFgGAGgEAGIgGAIIgGAJIgFAJIgFAKIgFAKYgBAEgBADgBAEYgDAHgCAHgBAIYgBAHgCAIAAAGYAAAIgBAFAAAHIABAMIABALYADAOAEAOAGAOYAHANAHAMAJAMYAIALAKALALAIYAGAFAGADAHAEYAGACAHADAHACYAGACAHABAHAAYAIABAFAAAGAAYANgBAOgCAMgFYAZgJAUgQAOgSYADgEADgFADgEYAEgFACgEADgEYAEgJAEgJADgJYAGgRADgQAAgNYAAgGAAgGgBgDYAAgFAAgEgBgDYgBgHgBgDAAAA");
	this.shape_2.setTransform(62,107.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#330000").s().p("AB5gpIieAOIgCAAIgQAFYgGACgFACgFACIgHAEYgDABgCABgDACIgOAIYgCAAgCABgDABIgGAFYgCACgDABgCACIgGAGIgGAFYgCACgCACgBACIgKANIAAAAIAMgLYACgBACgCACgBIAHgFIAGgEYACgBADgBACgCIAHgDYACgBACgBADgBIAPgGYACAAADgCACAAIAIAAYAFgBAFgCAFAAIAOgCIgBAAICeAMYAOABAMgIABgOYABgOgKgMgOgBYgBAAgCAAgBAA");
	this.shape_3.setTransform(68.9,82.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#330000").s().p("AhJhFIB8A8IgFgFIAVAdIgBgCIACAGYABACABACAAACYACAEABAEABAFYABAEABAEABAEYAAAFABAEAAAFYABAEAAAFAAAEYAAAEAAAFAAAEYAAAFAAAFAAAEIgCAOIAAAAIAEgOYABgEABgFABgEYABgEAAgFABgFYABgEAAgFABgEYAAgFAAgFAAgEYABgFgBgFAAgFYAAgEgBgFAAgFYgBgCAAgCgBgDIgBgHIgBgBIgOggYgBgCgBgBgBgBIgCgBIhwhRYgLgIgQADgIALYgIALADAQALAIYABABACABABAA");
	this.shape_4.setTransform(99.2,92.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("ABcADYgHABgGACgGACYAAAAgBABAAAAIAAAAIgFANIAAgBYgBABgBABAAACYgBABgCACgBABYAAAAgBABAAAAIgBABIgDACIgFAEIgCACIgDABYgCACgBABgCABYgCABgBABgCAAYgCABgBAAgCABIAGAEIgDgNIgDgMYgBgCAAgCgBgCIgCgGYgCgEgBgEgCgEIgGgJYgCgEgCgEgCgEYgCgDgCgEgDgDIgFgLYAAAAgBAAAAAAIgHgGYgCgBgDgCgCgCYgCgBgDgBgDgBYgDgCgDAAgDgBYgDgBgDABgDgBYgDABgDAAgDAAYgDABgDABgDABYgCACgDABgDABIAAABYAAAAgBAAAAAAYgHAJgHAJgHAJIAAAAYAKgGAJgHAJgHIgBABYADgBACgBACgCYACAAADgBACgBYACAAADAAACgBYADABACgBACABYADABACAAACABYADABACABACABYACACACABACABIAGAFIAAAAIAHAKYACADABADABAEYACADADAEACADIAFAJYACADABAEABAEIACAGYABACABACAAACIAEALIACAMIAAABYAAACADACACAAIAAAAYADgBADAAACgBYACgBACgBACgCYADgBABgBACgBIADgCIACgCIAFgEIADgCIABgBYABgBAAAAAAgBYACgBACgCACgCYABgCABgCABgDIAAAAIABgMIgBABYAGgDAFgEAFgDIAAAA");
	this.shape_5.setTransform(71.8,8.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("Ag9AcYgFgFgEgEgEgEIgGgGYgDgCgCgBgDgCIAAAJIAWgJIAWgGIAYgGIAVgEIAYgDIAXgCIAMAAYAEAAAEABAEgBYAIgBAIgBAJgBIAAAAYgIgCgIgCgIgCYgEgBgFAAgEAAIgMAAIgYACIgYADIgXAFIgXAGIgYAIIgWAHIgBAAYgCABgBADABACYAAABABABABAAYACACACACADABIAIAEYAGACAFADAGACIAAAA");
	this.shape_6.setTransform(129.3,2.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AheBPYAAAAADgCAFgFYACgDADgDAEgDYABgCACgCACgCYACgCACgCACgCYADgEAEgFAFgFYAEgFAFgFAFgFYAFgFAGgFAGgFYADgDADgCADgCIAJgGYAFgFAFgFAGgEYAGgFAGgEAGgEYAMgJAMgGAKgHYADgBACgBACgCYADgCACgBABgCYAEgDAEgCACgCYAGgFADgCAAAAIAAAAYAAAAgEABgHACYgDACgEABgEACYgDABgCAAgDABYgCACgCABgDACYgKAGgMAHgMAIYgGAFgHAEgGAFYgFAEgFAFgHAFIgJAHYgDADgDADgDABYgFAEgGAFgGAGYgFAFgFAFgFAFYgEAFgEAFgEAFYgCACgCACgCACYgBADgCACgBACYgCAEgCAEgBADYgDAHgCADAAAAIAAAA");
	this.shape_7.setTransform(104.5,35.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgLgbIAAAAIAAAAYABAAgBABgBABYgCABgDgBAAAAIgBgBYAAAAAAAAAAAAYAAAAABABAAABYACABABACADADYACADACAEADADYACAEACAEACACYACAEADAEACAEYACACABACABACYABACABABAAACYAEAGACAFAAAAIAAAAYAAAAgBgFgDgHYgBgBgBgCAAgCYgBgCgBgCgBgCYgCgEgCgFgCgEYgCgDgCgEgCgEYgBgEgCgEgBgDYgCgDgCgDgBgCYAAgBgBgBAAgBYgBAAAAAAAAAAIgBgBYAAAAgDgBgCABYgCABAAABAAAAIAAAAIAAAAIgBACYgBACABADADABYACABADgBABgCYAAAAAAAAAAgB");
	this.shape_8.setTransform(128.8,48.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(1,1,1).p("ADBo4IB4j9QAbgPAlgIQBRgSBMAMQAPAEAtAZQAXANATALACmpWQAWjyCujXQBeh1BsgwAIBGEQABgCAYgUQAPgMAKgOQA1hLgHg+QgGg9g6g8Qg/g5gNgWQgRgZAIh0QANiGABgwQAEgzhAg+IhBg0Qg1gphIgeQgLgFgUgHQiEguhvAnQh9Ash4COQg8BHgjA/QABgEgNAGQgbALhHAvQiHBaAAIeQAAC+ARC7QAPCnANAWQAOAXAsApQA1AxA6AlQCjBoBsg2QA/ggDikqQDSkTA0gjQADgDADgBQA2gZAPgZQAIgNAFgNQACgFAKgtQAKgtACAAgABypSQAbkAgckEAmagZQAABjAnBZQgFAUACBeQACCFAbB2QAjCWATA0QAaBFAoAdQAtAgAHAEQAeARAeABQBMAAB3hyQAIgIAkgeQAigdAOgNIAygKQAggoATgeQANgVAEgOQAnAGAmgIQAWgFAKgDAhzG2IAHAEICNA8QCjA9BdAKIADAAAhzG2IgNAxQgKA4ANAjQARArCAAqQBlAhA1gIAlzCjQA6CECQBqQAPALAnAaAIMEMQAFAegQBa");
	this.shape_9.setTransform(63.6,125.3);

	this.shape_10 = new cjs.Shape();
	//his.shape_10.graphics.lf(["#171717","#2D2E33"],[0,1],143,179,143,179).s().p("AgMFnQgdgBgegRIg0gkQgpgdgZhFQgUg0giiWQgbh0gDiFQgCheAGgUQA6CECQBqIA2AlIgNAxQgKA2ANAjQAQArCAAqQBlAhA1gIQgOANgiAdIgsAmQh5ByhJAAIgBAAg");
    this.shape_10.graphics.f("#000000").s().p("AgMFnQgdgBgegRIg0gkQgpgdgZhFQgUg0giiWQgbh0gDiFQgCheAGgUQA6CECQBqIA2AlIgNAxQgKA2ANAjQAQArCAAqQBlAhA1gIQgOANgiAdIgsAmQh5ByhJAAIgBAAg");
	this.shape_10.setTransform(53.5,177.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#E16027","#E7A32C"],[0,1],-10.1,8,8.1,-2.1).s().p("AA/CYQhzgtgrgZQgqgagfgfQgggdgJg6QgJg7A3gpQA4gpBEAJQBCAIAlAWQAaAPATAlQAIAPANAmIAPAxQAKAhAMAbQAeBDAIAXQAHAXgBADIgCAFQAAAKgHAHQgHAIgIAAIAAAAQgIAAh0gsg");
	this.shape_11.setTransform(84,141.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("ABQBUQgUgVgBgcQABgeAUgSQAVgVAcAAQAeAAAUAVQAVASAAAeQAAAcgVAVQgUAUgeABQgcgBgVgUgAiyAOQgUgSAAgeQAAgcAUgVQAVgUAcgBQAdABAVAUQAVAVgBAcQABAegVASQgVAVgdAAQgcAAgVgVg");
	this.shape_12.setTransform(74.5,111.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AmYNHQg6gkg0gyQgtgpgNgXQgNgVgPioQgRi7AAi+QAAoeCHhaQBGgvAbgLQAOgFgBADQAjg+A8hHQB4iPB9gsQBugnCEAvIAfALQBJAeA0ApIBBA1QBAA+gEAyQgBAwgNCGQgIB0ARAbQANAWA/A5QA6A9AGA8QAHA+g1BKQgKANgPANIgZAVQAMhDAAgfQAAgMgBgIQABAIAAAMQAAAfgMBDQgBABgKAsQgKAugDAEQgFAOgIAMQgOAag3AYIgGAEIggAIIgBAAQgWAFgWAAIgBAAIAAAAQgPAAgPgCIgBAAIABAAQAPACAPAAIAAAAIABAAQAWAAAWgFIABAAIAggIQgzAjjTEUQjhEqg/AfQglATgsAAQhTAAhshFgAlpgiQADCCAbB2QAiCXAUA0QAZBEApAdIA0AkQAeASAdAAQBMABB3hzIAsgmQAigcAOgOQg1AIhlggQiAgqgQgsQgNgiAKg4IANgyIAGAFICOA7QCiA+BeAJIACABIgCgBQhegJiig+IiOg7IgGgFIg2gkQiQhog6iEQgGAUACBegAEgEmQgSAeghAoIgyAKIAygKQAhgoASgeQANgUAEgOQgEAOgNAUgAA1k5Qg2ApAIA6QAJA6AfAgQAfAfArAZQAqAaB1ArQB1AsAIAAQAHgBAHgHQAIgHAAgLIABgFQACgCgIgVQgIgXgdhDQgMgcgLgiIgPgxQgNgngHgPQgTgkgagQQglgVhEgJIgYgBQg2AAguAigAlliUQgnhZAAhmQAABmAnBZgAGQmfQgCApgNAgQgNAfgtAlQAtglANgfQANggACgpIAAgKQAAgqgSggQgFgIgOgMQgQgOgPgGQgVgIgUgDIgCAAIgBgBIgDAAIgNgBIgBAAIAAAAQgKAAgHACIgBABIgBAAIAAAAQgbAIgNAMQgIAHgNAPQgOARgFALQgPAagFAiIAAAyIAAgyQAFgiAPgaQAFgLAOgRQANgPAIgHQANgMAbgIIAAAAIABAAIABgBQAHgCAKAAIAAAAIABAAIANABIADAAIABABIACAAQAUADAVAIQAPAGAQAOQAOAMAFAIQASAgAAAqIAAAKgAgLlLIALgBIAAAAQBBgGAng4QAfguAAgzIgCgXIACAXQAAAzgfAuQgnA4hBAGIAAAAIgLABIAAAAIgBAAQg1gBghgpIAAAAIgDgEQgkgwAAgxIABgHQACg1AWgkQAWglAUgNQAUgOAdgEIAAAAIATgBIAAAAIABAAQApAAAnAbIAAAAIABABIABABQAsAgAIBAQgIhAgsggIgBgBIgBgBIAAAAQgngbgpAAIgBAAIAAAAIgTABIAAAAQgdAEgUAOQgUANgWAlQgWAkgCA1IgBAHQAAAxAkAwIADAEIAAAAQAhApA1ABIABAAIAAAAgADKnUQgUAUAAAdQAAAdAUAVQAVAUAdAAQAdAAAUgUQAVgVAAgdQAAgdgVgUQgUgVgdAAQgdAAgVAVgAg4oaQgUAUAAAdQAAAdAUAVQAVAUAdAAQAbAAAUgUQAVgVAAgdQAAgdgVgUQgUgVgbAAQgdAAgVAVgAG/oMQAFgcAAgZQAAgegIgYIgRghIh4hGIB4BGIARAhQAIAYAAAeQAAAZgFAcgAgLrmQgtARgZAfQAZgfAtgRQAUgJASgDICgAAIigAAQgSADgUAJgAGeD5IAAAAg");
	this.shape_13.setTransform(62.3,156.7);

	this.addChild(this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-0.4,140.1,249);


(lib.OlafRighLeg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AhcEQQCIBHBvgqQBvgqAOiLQAPiJgQh4QgQh5htgnQhtgmhCApQhEAphyBpQhzBpAsB5QAsB7CKBHg");
	this.shape.setTransform(28.8,31.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhcEQQiKhHgsh7Qgsh5BzhpQByhpBEgpQBCgpBtAmQBtAnAQB5QAQB4gPCJQgOCLhvAqQgpAPgtAAQhKAAhXgsg");
	this.shape_1.setTransform(28.8,31.7);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,59.6,65.4);


// stage content:
(lib.olaf_tween_Canvas = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_44 = function() {
		//
		///* Stop a Movie Clip
		//Stops the specified movie clip on stage.
		//
		//Instructions:
		//1. Use this code for movie clips that are currently playing.
		//*/
		//
		//stop();
        document.getElementById("greeting").className = "shown";
        document.getElementById("signed").className = "shown";
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(44).call(this.frame_44).wait(1));

	// Layer 1
	this.instance = new lib.olafHead();
	this.instance.setTransform(108,279,1,1,-17,0,0,21.9,237.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:403,y:263},22).wait(4).to({y:265},3).wait(6).to({regY:237.2,scaleX:1,scaleY:1,rotation:-16.8,y:265.1},4).to({regY:237.1,scaleX:1,scaleY:1,rotation:-17,y:265},5).wait(1));

	// Layer 9
	this.instance_1 = new lib.OlafRighLeg();
	this.instance_1.setTransform(68.1,426.1,1,1,0,0,0,39.8,14.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:41.6,regY:9.5,rotation:-81.2,x:213.1,y:418},6).to({regX:44.8,regY:8.8,rotation:-20.5,x:226.1},6).to({regX:41.1,regY:7.7,rotation:-29.2,x:358.1,y:410.1},5).to({regX:45.6,regY:10.2,rotation:-27.2,x:373,y:407.1},5).wait(13).to({scaleX:1,scaleY:1,rotation:-27.1,x:373.1},4).to({scaleX:1,scaleY:1,rotation:-27.2,x:373},5).wait(1));

	// Layer 3
	this.instance_2 = new lib.olafRighArm();
	this.instance_2.setTransform(84,296,1,1,25.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({rotation:47.2,x:159.6,y:292.2},6).to({scaleX:1,scaleY:1,rotation:18.1,x:240.1,y:288.5},6).to({regY:1,scaleX:1,scaleY:1,rotation:0,x:383,y:281},10).to({regY:0,rotation:11.7,y:282},7).wait(16));

	// Layer 2
	this.instance_3 = new lib.OlafUpperBod();
	this.instance_3.setTransform(110.6,301.7,1,1,0,0,0,46.6,36.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:409.6,y:285.7},22).wait(4).to({y:287.7},3).wait(16));

	// Layer 5
	this.instance_4 = new lib.OlafLowerBod();
	this.instance_4.setTransform(112,340,1,1,9.2,0,0,68.9,21.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:411,y:324},22).wait(4).to({y:326},3).wait(16));

	// Layer 4
	this.instance_5 = new lib.OlafLeftArm();
	this.instance_5.setTransform(150.5,293.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:0.95,scaleY:0.98,rotation:-2.9,x:225.3,y:289.5},6).to({scaleX:0.98,scaleY:0.99,rotation:56.7,x:374.8,y:281.5},12).to({scaleX:1,scaleY:1,rotation:0,x:449.5,y:277.5},8).to({rotation:-103.6,x:441.3,y:261.7},4).to({rotation:-117.5,x:439.8,y:262.9},2).to({rotation:-103.3,x:441.3,y:264.8},2).to({rotation:-117.5,x:439.8,y:264.9},2).to({rotation:-103.3,x:441.3,y:263.8},2).to({y:265.8},2).to({rotation:10,x:449.5,y:277.5},4).wait(1));

	// Layer 7
	this.instance_6 = new lib.OlafLeftLeg();
	this.instance_6.setTransform(170,420.1,1,1,0,0,0,19.5,15.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({regX:16.4,regY:15,rotation:66,y:415},6).to({regX:8.3,regY:15.5,rotation:7.8,x:319,y:399},6).to({regX:13.7,regY:11.5,rotation:74.7,x:320.9,y:382.1},5).to({regX:10.1,regY:13.7,rotation:30.3,x:450.4,y:406.4},5).to({rotation:30.3},4).to({y:408.4},3).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(337.1,257.4,220,457.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;